---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Load user description data
      include_vars:
        file: "{{ users_dir }}/{{ target_user }}.yml"
        name: user_data
    - name: Configure git environment for the user
      include_role:
        name: manage-user
        tasks_from: git.yml
    - name: "Install Python dependencies"
      include_role:
        name: python
    - name: Update configuration repositories and deploy XDG compliant configuration elements
      include_role:
        name: manage-user
        tasks_from: xdg-conf.yml
      loop: "{{ user_data['configurations']|dict2items }}"
      loop_control:
        loop_var: user_conf
    - name: Deploy non XDG compliant configuration elements
      include_role:
        name: manage-user
        tasks_from: non-xdg-conf.yml
