---
- hosts: localhost
  gather_facts: False
  vars:
    xdg_config_home: "~/.config"
  tasks:
    - name: Load user description data
      include_vars:
        file: "{{ users_dir }}/{{ target_user }}.yml"
        name: user_data
    - include: tasks/git.yml
    - include: tasks/python.yml
    - include: tasks/tmux.yml
      when: user_data.tmux
    - include: tasks/zsh.yml
      when: user_data.zsh
    - include: tasks/emacs.yml
      when: user_data.emacs
    - name: Deploy XDG compliant configuration elements
      include_tasks: tasks/xdg-conf.yml
      loop: "{{ user_data['configurations']|dict2items }}"
      loop_control:
        loop_var: user_conf
