# The host user must be root.
---
- hosts: all
  gather_facts: False
  tasks:
    - name: Load user description data
      include_vars:
        file: "{{ users_dir }}/{{ target_user }}.yml"
        name: user_data
    - name: "Create user environment"
      include_role:
        name: manage-user
        tasks_from: main.yml
    - name: Configure git environment for the user
      include_role:
        name: manage-user
        tasks_from: git.yml
    - name: "Install Python dependencies"
      include_role:
        name: python
