- name: "Install pipenv"
  pip:
    name: pipenv
    executable: 'pip-3'
    extra_args: "--user"
    state: latest

- name: Installing packages for developers
  pip:
    name: "{{ item }}"
    executable: 'pip-3'
    extra_args: "--user"
    state: latest
  loop:
    - ansible-generator
    - ansible-lint
  when: user_data.dev_profile
