- name: Ensure .tmux directory is empty
  file:
    path: "~/.tmux"
    state: absent
- name: Deploy configuration files
  copy:
    src: "tmux/{{ item }}"
    dest: "~/.{{ item }}"
    remote_src: 'yes'
  loop:
    - tmux
    - tmux.conf
